# Configuration for alacritty

ipc_socket = true
live_config_reload = true
shell = "/usr/bin/bash"

[bell]
animation = "Linear"
command = "None"
duration = 0

[colors]

[cursor]
style.blinking = "Never"
style.shape = "Block"
thickness = 0.1
unfocused_hollow = true
vi_mode_style = "None"

[debug]

[env]
TERM = "xterm-256color"
# WINIT_X11_SCALE_FACTOR = "1.0"

[font]
bold = { family = "hack", style = "Bold" }
bold_italic = { family = "hack", style = "Bold Italic" }
italic = { family = "hack", style = "Italic" }
normal = { family = "hack", style = "Regular" }
size = 7

[hints]
alphabet = "asdfghjkl;"

[keyboard]

bindings = [
{ key = "h", mods = "Control|Shift", chars = "\uE000" },
{ key = "j", mods = "Control|Shift", chars = "\uE001" },
{ key = "k", mods = "Control|Shift", chars = "\uE002" },
{ key = "l", mods = "Control|Shift", chars = "\uE003" },

{ key = "%", mods = "Control|Shift", chars = "\uE004" },
{ key = "\"", mods = "Control|Shift", chars = "\uE005" },
{ key = "Space", mods = "Control|Shift", chars = "\uE006" },

{ key = "1", mods = "Control", chars = "\uE007" },
{ key = "2", mods = "Control", chars = "\uE008" },
{ key = "3", mods = "Control", chars = "\uE009" },
{ key = "4", mods = "Control", chars = "\uE00a" },
{ key = "5", mods = "Control", chars = "\uE00b" },
{ key = "6", mods = "Control", chars = "\uE00c" },
{ key = "7", mods = "Control", chars = "\uE00d" },
{ key = "8", mods = "Control", chars = "\uE00e" },
{ key = "9", mods = "Control", chars = "\uE00f" },
]

[mouse]

[scrolling]
history = 100000
multiplier = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[terminal]
osc52 = "CopyPaste"

[window]
class = { instance = "Alacritty", general = "Alacritty" }
decorations = "None"
decorations_theme_variant = "None"
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"
title = "Alacritty"
